Bump MSRV to 1.54
This is mainly to work around a very annoying bug in 1.51 which prevents
publishing any of the crates in this repo:

```
   Packaging cosmos_sdk v0.3.0 (src/cosmos-rust/cosmos-sdk-rs)
error: failed to prepare local package for uploading

Caused by:
  values must be emitted before tables
```

I'm not sure what the root cause is exactly, but whatever it is it
appears to be fixed in newer versions of Rust.

This commit bumps to 1.54, which is the latest stable release.